const sb=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);let docs=[];
function msg(id,t,err=false){const x=document.getElementById(id);x.textContent=t;x.className='msg '+(err?'error':'ok');}
async function boot(){const {data:{session}}=await sb.auth.getSession(); if(session) await showDash(session.user);}
async function login(){const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)return msg('login-msg',error.message,true);await showDash(data.user);}
async function showDash(user){const {data:p}=await sb.from('profiles').select('role,full_name').eq('id',user.id).single();if(p?.role!=='admin'){await sb.auth.signOut();return msg('login-msg','Tài khoản này chưa được cấp quyền quản trị.',true);}document.getElementById('login-box').hidden=true;document.getElementById('dashboard').hidden=false;await refresh();}
async function logout(){await sb.auth.signOut();location.reload();}
async function refresh(){const {data:cats}=await sb.from('categories').select('*').order('name');document.getElementById('doc-category').innerHTML=(cats||[]).map(c=>`<option value="${c.id}">${c.name}</option>`).join('');const {data:d}=await sb.from('documents').select('*,categories(name)').order('created_at',{ascending:false});docs=d||[];document.getElementById('stat-docs').textContent=docs.length;document.getElementById('stat-pdf').textContent=docs.filter(x=>x.file_type.includes('pdf')).length;document.getElementById('stat-word').textContent=docs.filter(x=>x.file_type.includes('word')).length+docs.filter(x=>x.file_type.includes('document')).length;document.getElementById('stat-downloads').textContent=docs.reduce((a,x)=>a+(x.downloads||0),0);document.getElementById('admin-docs').innerHTML=docs.map(d=>`<div class="admin-item"><div><b>${d.title}</b><small>${d.categories?.name||''} • ${d.file_type}</small></div><div><a class="btn small" href="${sb.storage.from('documents').getPublicUrl(d.file_path).data.publicUrl}" target="_blank">Xem</a><button class="btn small danger" onclick="deleteDoc(${d.id},'${d.file_path.replace(/'/g,"\\'")}')">Xóa</button></div></div>`).join('')||'Chưa có tài liệu.';const {data:n}=await sb.from('news').select('*').order('created_at',{ascending:false});document.getElementById('admin-news').innerHTML=(n||[]).map(x=>`<div class="admin-item"><div><b>${x.title}</b><small>${new Date(x.created_at).toLocaleDateString('vi-VN')}</small></div><button class="btn small danger" onclick="deleteNews(${x.id})">Xóa</button></div>`).join('')||'Chưa có tin.';}
async function uploadDoc(){const f=document.getElementById('doc-file').files[0];if(!f)return msg('upload-msg','Chọn file PDF/DOC/DOCX.',true);if(f.size>20*1024*1024)return msg('upload-msg','File tối đa 20MB.',true);const title=document.getElementById('doc-title').value.trim()||f.name;const safe=f.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${Date.now()}-${crypto.randomUUID()}-${safe}`;msg('upload-msg','Đang upload...');let {error}=await sb.storage.from('documents').upload(path,f,{contentType:f.type||'application/octet-stream',upsert:false});if(error)return msg('upload-msg',error.message,true);const category_id=document.getElementById('doc-category').value||null;({error}=await sb.from('documents').insert({title,category_id,description:document.getElementById('doc-desc').value,file_name:f.name,file_path:path,file_type:f.type,file_size:f.size,featured:document.getElementById('doc-featured').checked}));if(error){await sb.storage.from('documents').remove([path]);return msg('upload-msg',error.message,true);}document.getElementById('doc-title').value='';document.getElementById('doc-desc').value='';document.getElementById('doc-file').value='';document.getElementById('doc-featured').checked=false;msg('upload-msg','Upload thành công.');await refresh();}
async function deleteDoc(id,path){if(!confirm('Xóa tài liệu này?'))return;const {error}=await sb.from('documents').delete().eq('id',id);if(error)return alert(error.message);await sb.storage.from('documents').remove([path]);await refresh();}
async function addNews(){const title=document.getElementById('news-title').value.trim(),content=document.getElementById('news-content').value.trim();if(!title||!content)return msg('news-msg','Nhập tiêu đề và nội dung.',true);const {error}=await sb.from('news').insert({title,content,image_url:document.getElementById('news-image').value.trim()||null});if(error)return msg('news-msg',error.message,true);document.getElementById('news-title').value='';document.getElementById('news-content').value='';document.getElementById('news-image').value='';msg('news-msg','Đăng tin thành công.');await refresh();}
async function deleteNews(id){if(!confirm('Xóa tin này?'))return;const {error}=await sb.from('news').delete().eq('id',id);if(error)return alert(error.message);await refresh();}
boot();
