const SUPABASE_URL="https://cwupmehkajtwydwmgntj.supabase.co";
const SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zY3djYnJnY2treWZ4cGdwc3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAwNTc5NDEsImV4cCI6MjEwNTYzMzk0MX0.zibHWfICPmCXurCvt1yRKbQMGFjeXxl6kWD_suPZF0o";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),date=d=>d?new Intl.DateTimeFormat("vi-VN",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(d)):"";
let docs=[],albums=[],news=[],videos=[],users=[],cats=[];
function openModal(html){$("modalBody").innerHTML=html;$("modal").classList.remove("hidden")}function closeModal(){$("modal").classList.add("hidden")}
document.addEventListener("click",e=>{if(e.target.hasAttribute("data-close"))closeModal()});
$("logout").onclick=async()=>{await sb.auth.signOut();location.reload()};
$("login").onclick=async()=>{let {error}=await sb.auth.signInWithPassword({email:$("email").value.trim(),password:$("pass").value});if(error){$("msg").textContent=error.message;return}await boot()};
async function boot(){let {data:{user}}=await sb.auth.getUser();if(!user)return;let {data:p}=await sb.from("profiles").select("*").eq("id",user.id).single();if(!p||p.role!=="admin"){$("msg").textContent="Tài khoản chưa được cấp quyền admin.";return}$("loginPanel").classList.add("hidden");$("dashboard").classList.remove("hidden");refresh()}
async function refresh(){let [d,a,n,v,u,c]=await Promise.all([sb.from("documents").select("*").order("created_at",{ascending:false}),sb.from("albums").select("*").order("created_at",{ascending:false}),sb.from("news").select("*").order("published_at",{ascending:false}),sb.from("media").select("*").eq("media_type","video").order("created_at",{ascending:false}),sb.from("profiles").select("*").order("created_at"),sb.from("categories").select("*").order("sort_order")]);docs=d.data||[];albums=a.data||[];news=n.data||[];videos=v.data||[];users=u.data||[];cats=c.data||[];$("stats").innerHTML=[["📚",docs.length,"Tài liệu"],["📸",albums.length,"Album ảnh"],["📰",news.length,"Tin hoạt động"],["🎬",videos.length,"Video"],["👥",users.length,"Tài khoản BCH"]].map(x=>`<div class="stat"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join("");renderDocs();renderAlbums();renderNews();renderVideos();renderUsers()}
function renderDocs(){$("adminDocs").innerHTML=docs.map(x=>`<div class="admin-row"><div><b>${esc(x.title)}</b><small>${esc(x.category)} · ${date(x.created_at)} · 👁 ${x.view_count||0} · ⬇ ${x.download_count||0}</small></div><div><button class="ghost-btn" data-edit-doc="${x.id}">✏️ Sửa</button><button class="danger-btn" data-del-doc="${x.id}">🗑️ Xóa</button></div></div>`).join("")||'<p class="muted">Chưa có tài liệu.</p>';document.querySelectorAll("[data-edit-doc]").forEach(b=>b.onclick=()=>docForm(b.dataset.editDoc));document.querySelectorAll("[data-del-doc]").forEach(b=>b.onclick=()=>delDoc(b.dataset.delDoc))}
function renderAlbums(){$("adminAlbums").innerHTML=albums.map(x=>`<div class="admin-row"><div class="admin-news-row">${x.cover_url?`<img class="admin-thumb" src="${esc(x.cover_url)}">`:""}<div><b>${esc(x.title)}</b><small>${date(x.created_at)} · ${x.is_published?"Công khai":"Ẩn"}</small></div></div><div><button class="ghost-btn" data-edit-album="${x.id}">✏️ Sửa</button><button class="danger-btn" data-del-album="${x.id}">🗑️ Xóa</button></div></div>`).join("")||'<p class="muted">Chưa có album.</p>';document.querySelectorAll("[data-edit-album]").forEach(b=>b.onclick=()=>albumForm(b.dataset.editAlbum));document.querySelectorAll("[data-del-album]").forEach(b=>b.onclick=()=>delAlbum(b.dataset.delAlbum))}
function renderNews(){$("adminNews").innerHTML=news.map(x=>`<div class="admin-row"><div class="admin-news-row">${x.cover_url?`<img class="admin-thumb" src="${esc(x.cover_url)}">`:""}<div><b>${esc(x.title)}</b><small>${date(x.published_at)} · ${x.is_published?"Công khai":"Ẩn"}</small></div></div><div><button class="ghost-btn" data-edit-news="${x.id}">✏️ Sửa</button><button class="danger-btn" data-del-news="${x.id}">🗑️ Xóa</button></div></div>`).join("")||'<p class="muted">Chưa có tin.</p>';document.querySelectorAll("[data-edit-news]").forEach(b=>b.onclick=()=>newsForm(b.dataset.editNews));document.querySelectorAll("[data-del-news]").forEach(b=>b.onclick=()=>delNews(b.dataset.delNews))}
function renderVideos(){$("adminVideos").innerHTML=videos.map(x=>`<div class="admin-row"><div><b>${esc(x.title)}</b><small>${date(x.created_at)}</small></div><button class="danger-btn" data-del-video="${x.id}">🗑️ Xóa</button></div>`).join("")||'<p class="muted">Chưa có video.</p>';document.querySelectorAll("[data-del-video]").forEach(b=>b.onclick=()=>delVideo(b.dataset.delVideo))}
function renderUsers(){$("adminUsers").innerHTML=users.map(x=>`<div class="admin-row"><div><b>${esc(x.full_name||"Chưa đặt tên")}</b><small>${esc(x.email||"")} · Vai trò: ${esc(x.role)}</small></div><button class="ghost-btn" data-role="${x.id}" data-newrole="${x.role==="admin"?"viewer":"admin"}">Đổi thành ${x.role==="admin"?"viewer":"admin"}</button></div>`).join("")||'<p class="muted">Chưa có hồ sơ.</p>';document.querySelectorAll("[data-role]").forEach(b=>b.onclick=async()=>{await sb.from("profiles").update({role:b.dataset.newrole}).eq("id",b.dataset.role);refresh()})}
async function currentUid(){return (await sb.auth.getUser()).data.user.id}
function docForm(id=""){let x=docs.find(z=>z.id===id)||{};openModal(`<h2>${id?"Sửa":"Thêm"} tài liệu</h2><input class="input" id="dt" value="${esc(x.title)}" placeholder="Tên tài liệu"><select class="input" id="dc">${cats.map(z=>`<option ${z.name===x.category?"selected":""}>${esc(z.name)}</option>`).join("")}</select><textarea class="textarea" id="dd" placeholder="Mô tả">${esc(x.description)}</textarea><input class="input" id="df" type="file" accept=".pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.jpg,.jpeg,.png,.webp,.zip"><label class="check"><input id="dp" type="checkbox" ${x.is_published!==false?"checked":""}> Công khai</label><button class="green-btn" id="saveDoc">Lưu tài liệu</button><p id="err" class="muted"></p>`);$("saveDoc").onclick=()=>saveDoc(id)}
async function saveDoc(id){let title=$("dt").value.trim(),category=$("dc").value,description=$("dd").value.trim(),file=$("df").files[0],pub=$("dp").checked;if(!title){$("err").textContent="Thiếu tên tài liệu.";return}let payload={title,category,description,is_published:pub};if(file){let uid=await currentUid(),path=`${uid}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`,up=await sb.storage.from("documents").upload(path,file);if(up.error){$("err").textContent=up.error.message;return}let type=file.type==="application/pdf"?"PDF":file.type.includes("word")?"DOCX":file.type.includes("presentation")?"PPTX":file.type.includes("spreadsheet")?"XLSX":"FILE";payload={...payload,storage_path:path,public_url:sb.storage.from("documents").getPublicUrl(path).data.publicUrl,file_name:file.name,file_type:type}}let r=id?await sb.from("documents").update(payload).eq("id",id):await sb.from("documents").insert(payload);if(r.error){$("err").textContent=r.error.message;return}closeModal();refresh()}
async function delDoc(id){if(!confirm("Xóa tài liệu?"))return;await sb.from("documents").delete().eq("id",id);refresh()}
async function albumForm(id=""){let x=albums.find(z=>z.id===id)||{},old=[];if(id){let r=await sb.from("album_images").select("*").eq("album_id",id).order("sort_order");old=r.data||[]}openModal(`<h2>${id?"Sửa":"Tạo"} album hình ảnh</h2><input class="input" id="at" value="${esc(x.title)}" placeholder="Tên album"><textarea class="textarea" id="ad" placeholder="Mô tả">${esc(x.description)}</textarea><label class="form-label">Ảnh album</label><input class="input" id="af" type="file" accept="image/jpeg,image/png,image/webp" multiple><div class="upload-hint">Có thể chọn nhiều ảnh cùng lúc, tối đa 8 MB/ảnh.</div><div id="apreview" class="upload-preview"></div>${old.length?`<label class="form-label">Ảnh đang có</label><div class="mini-gallery">${old.map((im,i)=>`<label><img src="${esc(im.image_url)}"><span><input type="checkbox" data-rm="${im.id}"> Xóa</span></label>`).join("")}</div>`:""}<label class="check"><input id="ap" type="checkbox" ${x.is_published!==false?"checked":""}> Công khai</label><button class="green-btn" id="saveAlbum">Lưu album</button><p id="ae" class="muted"></p>`);$("af").onchange=()=>{$("apreview").innerHTML=[...$("af").files].map(f=>`<img src="${URL.createObjectURL(f)}">`).join("")};$("saveAlbum").onclick=()=>saveAlbum(id,old)}
async function saveAlbum(id,old){let title=$("at").value.trim(),description=$("ad").value.trim(),files=[...$("af").files],pub=$("ap").checked;if(!title){$("ae").textContent="Thiếu tên album.";return}if(files.some(f=>!f.type.startsWith("image/")||f.size>8*1024*1024)){ $("ae").textContent="Ảnh phải là JPG/PNG/WebP và tối đa 8 MB.";return}$("ae").textContent=`Đang tải ${files.length} ảnh...`;let payload={title,description,is_published:pub};if(id){let r=await sb.from("albums").update(payload).eq("id",id);if(r.error){$("ae").textContent=r.error.message;return}}else{let r=await sb.from("albums").insert(payload).select("*").single();if(r.error){$("ae").textContent=r.error.message;return}id=r.data.id}let remove=[...document.querySelectorAll("[data-rm]:checked")].map(e=>e.dataset.rm);for(let rid of remove){let im=old.find(x=>x.id===rid);if(im?.image_path)await sb.storage.from("media").remove([im.image_path]);await sb.from("album_images").delete().eq("id",rid)}let {count}=await sb.from("album_images").select("*",{count:"exact",head:true}).eq("album_id",id);let start=count||0;for(let i=0;i<files.length;i++){let f=files[i],uid=await currentUid(),path=`albums/${uid}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`,up=await sb.storage.from("media").upload(path,f);if(up.error){$("ae").textContent=up.error.message;continue}let url=sb.storage.from("media").getPublicUrl(path).data.publicUrl;let r=await sb.from("album_images").insert({album_id:id,image_path:path,image_url:url,sort_order:start+i});if(r.error)await sb.storage.from("media").remove([path]);if(i===0&&!old.length&&!id){}}let first=await sb.from("album_images").select("*").eq("album_id",id).order("sort_order").limit(1).maybeSingle();if(first.data)await sb.from("albums").update({cover_url:first.data.image_url,cover_path:first.data.image_path}).eq("id",id);closeModal();refresh()}
async function delAlbum(id){if(!confirm("Xóa album và toàn bộ ảnh?"))return;let r=await sb.from("album_images").select("*").eq("album_id",id);let paths=(r.data||[]).map(x=>x.image_path).filter(Boolean);await sb.from("albums").delete().eq("id",id);if(paths.length)await sb.storage.from("media").remove(paths);refresh()}
function newsForm(id=""){let x=news.find(z=>z.id===id)||{};openModal(`<h2>${id?"Sửa":"Thêm"} tin hoạt động</h2><input class="input" id="nt" value="${esc(x.title)}" placeholder="Tiêu đề"><input class="input" id="nf" type="file" accept="image/*"><div class="upload-hint">Ảnh đại diện, tối đa 8 MB.</div><textarea class="textarea" id="ns" placeholder="Tóm tắt">${esc(x.summary)}</textarea><textarea class="textarea" id="nc" placeholder="Nội dung tin">${esc(x.content)}</textarea><input class="input" id="nimgs" type="file" accept="image/*" multiple><div class="upload-hint">Có thể chọn nhiều ảnh minh họa cho bài.</div><label class="check"><input id="np" type="checkbox" ${x.is_published!==false?"checked":""}> Công khai</label><button class="green-btn" id="saveNews">Lưu tin</button><p id="ne" class="muted"></p>`);$("saveNews").onclick=()=>saveNews(id)}
async function saveNews(id){let x=news.find(z=>z.id===id)||{},title=$("nt").value.trim(),summary=$("ns").value.trim(),content=$("nc").value.trim(),cover=$("nf").files[0],imgs=[...$("nimgs").files];if(!title){$("ne").textContent="Thiếu tiêu đề.";return}let payload={title,summary,content,is_published:$("np").checked,published_at:new Date().toISOString()};if(cover){let uid=await currentUid(),path=`news/${uid}/${crypto.randomUUID()}-${cover.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`,up=await sb.storage.from("media").upload(path,cover);if(up.error){$("ne").textContent=up.error.message;return}payload.cover_path=path;payload.cover_url=sb.storage.from("media").getPublicUrl(path).data.publicUrl}let r=id?await sb.from("news").update(payload).eq("id",id):await sb.from("news").insert(payload).select("*").single();if(r.error){$("ne").textContent=r.error.message;return}let nid=id||r.data.id;let old=await sb.from("news_images").select("*").eq("news_id",nid);let start=(old.data||[]).length;for(let i=0;i<imgs.length;i++){let f=imgs[i],uid=await currentUid(),path=`news/${uid}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`,up=await sb.storage.from("media").upload(path,f);if(up.error)continue;let url=sb.storage.from("media").getPublicUrl(path).data.publicUrl;await sb.from("news_images").insert({news_id:nid,image_path:path,image_url:url,sort_order:start+i})}closeModal();refresh()}
async function delNews(id){if(!confirm("Xóa tin và ảnh trong bài?"))return;let im=await sb.from("news_images").select("*").eq("news_id",id),x=news.find(n=>n.id===id),paths=(im.data||[]).map(i=>i.image_path).filter(Boolean);if(x?.cover_path)paths.push(x.cover_path);await sb.from("news").delete().eq("id",id);if(paths.length)await sb.storage.from("media").remove(paths);refresh()}
function videoForm(){openModal(`<h2>Thêm video</h2><input class="input" id="vt" placeholder="Tên video"><input class="input" id="vf" type="file" accept="video/mp4,video/webm"><label class="check"><input id="vp" type="checkbox" checked> Công khai</label><button class="green-btn" id="saveVideo">Tải lên</button><p id="ve" class="muted">Video dung lượng lớn có thể mất thời gian tải.</p>`);$("saveVideo").onclick=saveVideo}
async function saveVideo(){let title=$("vt").value.trim(),f=$("vf").files[0];if(!title||!f){$("ve").textContent="Nhập tên và chọn video.";return}let uid=await currentUid(),path=`videos/${uid}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`,up=await sb.storage.from("media").upload(path,f);if(up.error){$("ve").textContent=up.error.message;return}let url=sb.storage.from("media").getPublicUrl(path).data.publicUrl,r=await sb.from("media").insert({title,media_type:"video",storage_path:path,public_url:url,is_published:$("vp").checked});if(r.error){$("ve").textContent=r.error.message;return}closeModal();refresh()}
async function delVideo(id){if(confirm("Xóa video?")){await sb.from("media").delete().eq("id",id);refresh()}}
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.remove("active"));b.classList.add("active");["docs","albums","news","videos","users"].forEach(x=>$("tab-"+x).classList.toggle("hidden",x!==b.dataset.tab))});
$("addDoc").onclick=()=>docForm();$("addAlbum").onclick=()=>albumForm();$("addNews").onclick=()=>newsForm();$("addVideo").onclick=videoForm();
sb.auth.getSession().then(({data:{session}})=>{if(session)boot()});
