const sb = window.supabase.createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY);
const money=n=>n?`${(n/1024/1024).toFixed(1)} MB`:'';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const ready=()=>Boolean(window.SUPABASE_URL&&window.SUPABASE_ANON_KEY&&!window.SUPABASE_URL.includes('YOUR-'));
const fileIcon=t=>(t||'').includes('pdf')?'PDF':'DOC';
const docUrl=p=>sb.storage.from('documents').getPublicUrl(p).data.publicUrl;
async function loadHome(){if(!ready())return;const [dr,nr]=await Promise.all([sb.from('documents').select('*,categories(name)').eq('featured',true).order('created_at',{ascending:false}).limit(6),sb.from('news').select('*').order('created_at',{ascending:false}).limit(3)]);const docs=dr.data||[],news=nr.data||[];document.getElementById('featured').innerHTML=docs.map(d=>`<article class="doc-card"><div class="file-badge ${fileIcon(d.file_type)==='DOC'?'word':''}">${fileIcon(d.file_type)}</div><span class="tag">${esc(d.categories?.name||'Tài liệu')}</span><h3>${esc(d.title)}</h3><p>${esc(d.description||'Tài liệu được chia sẻ bởi Đoàn phường Tam Thắng.')}</p><a class="btn small" href="${docUrl(d.file_path)}" target="_blank" rel="noopener" onclick="countDownload(${d.id})">Xem / tải</a></article>`).join('')||'<div class="empty">Chưa có tài liệu nổi bật.</div>';document.getElementById('news').innerHTML=news.map(n=>`<article class="news-card"><span>${new Date(n.created_at).toLocaleDateString('vi-VN')}</span><h3>${esc(n.title)}</h3><p>${esc(n.content).slice(0,150)}${(n.content||'').length>150?'...':''}</p></article>`).join('')||'<div class="empty">Chưa có tin hoạt động.</div>'}
async function loadDocumentsPage(){if(!ready())return;const {data:cats}=await sb.from('categories').select('*').order('name');document.getElementById('category').innerHTML='<option value="">Tất cả danh mục</option>'+(cats||[]).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');window._docs=null;await renderDocs()}
async function renderDocs(){if(!ready())return;if(!window._docs){const {data}=await sb.from('documents').select('*,categories(name)').order('created_at',{ascending:false});window._docs=data||[]}const q=(document.getElementById('search')?.value||'').toLowerCase().trim(),cat=document.getElementById('category')?.value||'';const arr=window._docs.filter(d=>(!q||String(d.title||'').toLowerCase().includes(q)||String(d.description||'').toLowerCase().includes(q))&&(!cat||String(d.category_id)===cat));document.getElementById('doc-list').innerHTML=arr.map(d=>`<article class="doc-row"><div class="file-badge ${fileIcon(d.file_type)==='DOC'?'word':''}">${fileIcon(d.file_type)}</div><div class="doc-main"><span class="tag">${esc(d.categories?.name||'Tài liệu')}</span><h3>${esc(d.title)}</h3><p>${esc(d.description||'')}</p><small>${new Date(d.created_at).toLocaleDateString('vi-VN')} ${d.file_size?'• '+money(d.file_size):''}</small></div><div class="doc-actions"><a class="btn small" href="${docUrl(d.file_path)}" target="_blank" rel="noopener" onclick="countDownload(${d.id})">Mở / tải</a></div></article>`).join('')||'<div class="empty">Không tìm thấy tài liệu phù hợp.</div>'}
async function countDownload(id){try{await sb.rpc('increment_download',{p_id:id})}catch(e){}}
async function loadNewsPage(){if(!ready())return;const {data}=await sb.from('news').select('*').order('created_at',{ascending:false});document.getElementById('news-list').innerHTML=(data||[]).map(n=>`<article class="news-card large"><span>${new Date(n.created_at).toLocaleDateString('vi-VN')}</span><h2>${esc(n.title)}</h2><p>${esc(n.content)}</p>${n.image_url?`<img src="${esc(n.image_url)}" alt="${esc(n.title)}" loading="lazy">`:''}</article>`).join('')||'<div class="empty">Chưa có tin hoạt động.</div>'}
