-- THƯ VIỆN ĐOÀN PHƯỜNG TAM THẮNG - SUPABASE
-- Chạy toàn bộ file này trong Supabase > SQL Editor

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'user' check (role in ('admin','user')),
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  title text not null,
  category_id bigint references public.categories(id) on delete set null,
  description text,
  file_name text not null,
  file_path text not null unique,
  file_type text not null,
  file_size bigint default 0,
  featured boolean not null default false,
  downloads integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  image_url text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.documents enable row level security;
alter table public.news enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

drop policy if exists "profiles self read" on public.profiles;
create policy "profiles self read" on public.profiles for select using (id = auth.uid());

drop policy if exists "categories public read" on public.categories;
create policy "categories public read" on public.categories for select using (true);
drop policy if exists "categories admin insert" on public.categories;
create policy "categories admin insert" on public.categories for insert to authenticated with check (public.is_admin());
drop policy if exists "categories admin update" on public.categories;
create policy "categories admin update" on public.categories for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "categories admin delete" on public.categories;
create policy "categories admin delete" on public.categories for delete to authenticated using (public.is_admin());

drop policy if exists "documents public read" on public.documents;
create policy "documents public read" on public.documents for select using (true);
drop policy if exists "documents admin insert" on public.documents;
create policy "documents admin insert" on public.documents for insert to authenticated with check (public.is_admin());
drop policy if exists "documents admin update" on public.documents;
create policy "documents admin update" on public.documents for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "documents admin delete" on public.documents;
create policy "documents admin delete" on public.documents for delete to authenticated using (public.is_admin());

drop policy if exists "news public read" on public.news;
create policy "news public read" on public.news for select using (true);
drop policy if exists "news admin insert" on public.news;
create policy "news admin insert" on public.news for insert to authenticated with check (public.is_admin());
drop policy if exists "news admin update" on public.news;
create policy "news admin update" on public.news for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "news admin delete" on public.news;
create policy "news admin delete" on public.news for delete to authenticated using (public.is_admin());

insert into public.categories (name) values
('Văn bản Đoàn'),('Hướng dẫn - Nghiệp vụ'),('Kế hoạch - Báo cáo'),('Tuyên truyền - Giáo dục'),('Phong trào - Hoạt động')
on conflict (name) do nothing;

insert into public.news (title, content) values
('Chào mừng đến với Thư viện Đoàn phường Tam Thắng','Nơi tập hợp văn bản, tài liệu nghiệp vụ và thông tin hoạt động Đoàn phường Tam Thắng.'),
('Kho tài liệu trực tuyến','Tra cứu và tải tài liệu PDF, Word thuận tiện trên máy tính và điện thoại.')
on conflict do nothing;


create or replace function public.increment_download(p_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.documents set downloads = downloads + 1 where id = p_id;
end;
$$;
grant execute on function public.increment_download(bigint) to anon, authenticated;

-- Storage: tạo bucket tên documents trong Storage trước khi chạy các policy dưới đây.
-- Bucket nên để Public để người dân có thể xem/tải tài liệu.

create policy "documents storage public read"
on storage.objects for select
using (bucket_id = 'documents');

create policy "documents storage admin upload"
on storage.objects for insert to authenticated
with check (bucket_id = 'documents' and public.is_admin());

create policy "documents storage admin update"
on storage.objects for update to authenticated
using (bucket_id = 'documents' and public.is_admin())
with check (bucket_id = 'documents' and public.is_admin());

create policy "documents storage admin delete"
on storage.objects for delete to authenticated
using (bucket_id = 'documents' and public.is_admin());
